# Лабораторна робота 1
## Вступ до машинного навчання. Елементи лінійної алгебри




In [2]:
# === МЕТАДАНІ НОУТБУКА ===
surname = "Herasymenko"
variant = 1
created = "2025-10-28"
print(f"Очікувана назва файлу: {surname}_пр_{variant}.ipynb")

Очікувана назва файлу: Herasymenko_пр_1.ipynb


In [4]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

np.set_printoptions(suppress=True, precision=4)
print("Імпорти готові.")

Імпорти готові.


---
### Завдання 1.

In [7]:
# === Завдання 1. ===
# Умова:
# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та
#виведіть його значення

v = np.arange(1, 11)

# виводимо результат
print("Вектор з перших 10 натуральних чисел:")
print(v)


Вектор з перших 10 натуральних чисел:
[ 1  2  3  4  5  6  7  8  9 10]


---
### Завдання 2

In [9]:
# === Завдання 2 ===
# Умова:
# Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та
#виведіть його значення.

matrix = np.ones((4, 4))
print("Матриця 4x4, заповнена одиницями:")
print(matrix)



Матриця 4x4, заповнена одиницями:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


---
### Завдання 3

In [10]:
# === Завдання 3 ===
# Умова:
# Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні
#від 1 до 5 та виведіть його значення.

matrix = np.random.randint(1, 6, size=(4, 4))
print("Матриця 4x4 з випадковими цілими числами від 1 до 5:")
print(matrix)


Матриця 4x4 з випадковими цілими числами від 1 до 5:
[[1 1 5 2]
 [2 4 4 1]
 [1 3 3 5]
 [4 1 2 2]]


---
### Завдання 4

In [11]:
# === Завдання 4 ===
# Умова:
# Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
#діапазоні від 0 до 1 та виведіть його значення.

matrix = np.random.rand(3, 3)
print("Матриця 3x3 з випадковими дійсними числами [0, 1]:")
print(matrix)




Матриця 3x3 з випадковими дійсними числами [0, 1]:
[[0.997  0.8301 0.3079]
 [0.4732 0.1001 0.3928]
 [0.8855 0.5678 0.2738]]


---
### Завдання 5

In [12]:
# === Завдання 5 ===
# Умова:
# Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)




a = [ 6  1 18 15 11 14]
b = [12 17 17 12  6  3]
a + b = [18 18 35 27 17 17]
a - b = [ -6 -16   1   3   5  11]
a * b = [ 72  17 306 180  66  42]


---
### Завдання 6

In [13]:
# === Завдання 6 ===
# Умова:
# Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими
#числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання,
#віднімання та множення.

a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

print("a =", a)
print("b =", b)
print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)




a = [19 12 20 11  8  7]
b = [ 9 13  6 16 19  5]
a + b = [28 25 26 27 27 12]
a - b = [ 10  -1  14  -5 -11   2]
a * b = [171 156 120 176 152  35]


---
### Завдання 7

In [14]:
# === Завдання 7 ===
# Умова:
# Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
#в діапазоні від 1 до 10 та перемножте їх між собою.

A = np.random.randint(1, 11, size=(3, 2))
B = np.random.randint(1, 11, size=(2, 4))

print("A =\n", A)
print("B =\n", B)
print("A @ B =\n", A @ B)




A =
 [[4 9]
 [2 3]
 [7 7]]
B =
 [[ 3  1  8  2]
 [ 3  6 10  9]]
A @ B =
 [[ 39  58 122  89]
 [ 15  20  46  31]
 [ 42  49 126  77]]


---
### Завдання 8

In [15]:
# === Завдання 8 ===
# Умова:
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
#від 1 до 7 та знайдіть її обернену матрицю.

A = np.random.randint(1, 8, size=(2, 2))
print("A =\n", A)

det = np.linalg.det(A)
print("det(A) =", det)

if det != 0:
    invA = np.linalg.inv(A)
    print("Обернена матриця:\n", invA)
else:
    print("Матриця не має оберненої (det = 0).")




A =
 [[6 4]
 [5 5]]
det(A) = 10.000000000000002
Обернена матриця:
 [[ 0.5 -0.4]
 [-0.5  0.6]]


---
### Завдання 9

In [16]:
# === Завдання 9 ===
# Умова:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
#діапазоні від 0 до 1 та транспонуйте її.

A = np.random.rand(3, 3)
print("A =\n", A)
print("A^T =\n", A.T)




A =
 [[0.4976 0.1572 0.1485]
 [0.215  0.4147 0.331 ]
 [0.8819 0.9983 0.6366]]
A^T =
 [[0.4976 0.215  0.8819]
 [0.1572 0.4147 0.9983]
 [0.1485 0.331  0.6366]]


---
### Завдання 10

In [17]:
# === Завдання 10 ===
# Умова:
# Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
#цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор

A = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=(4, 1))

print("A =\n", A)
print("v =\n", v)
print("A @ v =\n", A @ v)




A =
 [[2 4 7 4]
 [1 2 7 2]
 [6 6 1 1]]
v =
 [[ 6]
 [ 9]
 [10]
 [ 4]]
A @ v =
 [[134]
 [102]
 [104]]


---
### Завдання 11

In [18]:
# === Завдання 11 ===
# Умова:
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
#випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
#числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

A = np.random.randint(1, 11, size=(2, 3))
v = np.random.randint(1, 11, size=(3, 1))

print("A =\n", A)
print("v =\n", v)
print("A @ v =\n", A @ v)




A =
 [[2 2 1]
 [8 1 9]]
v =
 [[4]
 [8]
 [8]]
A @ v =
 [[ 32]
 [112]]


---
### Завдання 12

In [19]:
# === Завдання 12 ===
# Умова:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 10 та знайдіть їхню суму.

A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

print("A =\n", A)
print("B =\n", B)
print("A + B =\n", A + B)




A =
 [[4 5]
 [1 7]]
B =
 [[3 4]
 [4 5]]
A + B =
 [[ 7  9]
 [ 5 12]]


---
### Завдання 13

In [20]:
# === Завдання 13 ===
# Умова:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в
#діапазоні від 0 до 1 та знайдіть їх добуток.

A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

print("A =\n", A)
print("B =\n", B)
print("A @ B =\n", A @ B)




A =
 [[0.1363 0.8449]
 [0.599  0.403 ]]
B =
 [[0.5695 0.3535]
 [0.3444 0.854 ]]
A @ B =
 [[0.3687 0.7697]
 [0.4799 0.5559]]


---
### Завдання 14

In [21]:
# === Завдання 14 ===
# Умова:
# Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
#діапазоні від 0 до 1 та знайдіть суму елементів матриці.

A = np.random.rand(5, 5)
print("A =\n", A)
print("Сума елементів матриці =", np.sum(A))



A =
 [[0.5526 0.2499 0.6345 0.2332 0.6101]
 [0.0847 0.7908 0.2202 0.8228 0.4155]
 [0.9038 0.0192 0.937  0.4416 0.9062]
 [0.5294 0.2659 0.5827 0.7315 0.8768]
 [0.7969 0.8447 0.1153 0.0977 0.11  ]]
Сума елементів матриці = 12.772887988879347


---
### Завдання 15

In [22]:
# === Завдання 15 ===
# Умова:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
#діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного
#рядка матриці.

A = np.random.uniform(-1, 1, size=(3, 3))
print("A =\n", A)

row_sums = np.sum(A, axis=1).reshape(-1, 1)
print("Вектор-стовпчик із сумою рядків:\n", row_sums)




A =
 [[ 0.846  -0.7277 -0.8329]
 [ 0.499  -0.8554 -0.172 ]
 [ 0.2348 -0.9143 -0.8681]]
Вектор-стовпчик із сумою рядків:
 [[-0.7145]
 [-0.5285]
 [-1.5475]]


---
## Висновок
*(У цій лабораторній роботі я навчилася створювати масиви та матриці в NumPy,
виконувати арифметичні операції, транспонування, добуток і знаходження обернених матриць.
Отримала практичні навички роботи з лінійною алгеброю в Python.
)*
